eureka.instance.instanceId : ${spring.profiles.active}_${spring.application.instance_id}-${server.poirt}
eureka.instance.preferIpAddress : false
eureka.instance.hostname : ${spring.profile}
eureka.clinet.registerWithEureka : ture
eureka.clinet.fetchRegistry : ture
eureka.clinet.serviceUrl.defaultZone : http://prd-eureka-commerce.is.ktds.co.kr:8092/eureka/